### ISSUE TITLE
xrdcp -f deletes a file in Ceph

### ISSUE THREAD

**Issue by george-patargias** [xrootd/xrootd-ceph#1]
Hello,

Following several tests we confirmed that "xrdcp -f" definitely deletes a Ceph file; The first attempt
to overwrite the file with "xrdcp -f" results in the following error.

Run: [ERROR] Server responded with an error: [3007] Unable to open dteam:overwritetest/test1; input/output error

Examining the "overwritten" file at the rados level, one sees that it is not just that the striper.size is set to 0, but that all data stripes are gone. Further attempts to overwrite this (deleted) file result in xrdcp hanging and occassionaly issuing the message "Output file alice:... is already opened by 1 writer; open denied".

There is an older github issue for this

https://github.com/xrootd/xrootd/issues/442

George

**Comment by simonmichal** [comment]
fixed in: 9e856d490c805928b3ace33150ea2256a5e00f82
